### ISSUE TITLE
How to sign up new user ?

### ISSUE THREAD

**Issue by Mei621** [aneesha/cbd#2]
Hello, I am new to Django and Python and I come across a problem at the login page of this system. At the login page, user are asked to login, but I can't find a place to sign up new users. How can I sign up new users? Thank you, I appreciate your help.

**Comment by Mei621** [comment]
haha, my problem solve

**Comment by pruthvipanchal** [comment]
hello, can you tell how you solved that problem ? coz am facing same issue, please replay asap.
